"""empty message

Revision ID: 1a07f2b2cade
Revises: fde9329bad8e
Create Date: 2021-10-12 08:48:52.212899

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a07f2b2cade'
down_revision = 'fde9329bad8e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('name', sa.String(length=50), nullable=False))
    op.drop_constraint('categories_category_name_key', 'categories', type_='unique')
    op.create_unique_constraint(None, 'categories', ['name'])
    op.drop_column('categories', 'category_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('category_name', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'categories', type_='unique')
    op.create_unique_constraint('categories_category_name_key', 'categories', ['category_name'])
    op.drop_column('categories', 'name')
    # ### end Alembic commands ###
