"""empty message

Revision ID: 185e6c0deddb
Revises: ffdc0a98111c
Create Date: 2021-10-11 13:07:23.643425

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '185e6c0deddb'
down_revision = 'ffdc0a98111c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(length=50), nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('name')
                    )
    op.create_table('projects',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('title', sa.String(length=50), nullable=False),
                    sa.Column('description', sa.Text(), nullable=False),
                    sa.Column('goal', sa.Integer(), nullable=False),
                    sa.Column('current_amount', sa.Integer(), nullable=False),
                    sa.Column('categories_id', sa.Integer(), nullable=False),
                    sa.Column('user_id', sa.Integer(), nullable=False),
                    sa.Column('image_url', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['categories_id'], ['categories.id'], ),
                    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('description'),
                    sa.UniqueConstraint('title')
                    )
    op.add_column('users', sa.Column('money', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'money')
    op.drop_table('projects')
    op.drop_table('categories')
    # ### end Alembic commands ###
